### ISSUE TITLE
Ruby Errors

### ISSUE THREAD

**Issue by fdrechsler** [hendricius/shuttle-cli#1]
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/shuttle_cli-0.0.3/lib/shuttle_cli.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/shuttle_cli-0.0.3/bin/shuttle:2:in `require_relative'
	from /usr/local/lib/ruby/gems/2.3.0/gems/shuttle_cli-0.0.3/bin/shuttle:2:in `<top (required)>'
	from /usr/local/bin/shuttle:22:in `load'
	from /usr/local/bin/shuttle:22:in `<main>'

**Comment by hendricius** [comment]
Yup sorry. Would be nice to have this working again. Pull requests are welcome 👍

**Comment by arayabravo** [comment]
There is any way to fix this problem?

Unfortunately i don't do code so i can't fix the problem myself.

**Comment by damniel** [comment]
This is a missing dependency if you installed a new rbenv as I did. Do a 
`gem install pry` 
and it should work after that.

**Comment by arayabravo** [comment]
Thanks Damniel.

Now it works.

**Comment by hendricius** [comment]
fixed it :). you can fetch the newest version from rubygems. `gem update shuttle_cli`
